# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChartsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for ChartsApp

pod 'ChartsLib', :path => '../ChartsLib'

  target 'ChartsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChartsAppUITests' do
    # Pods for testing
  end

end
